<<<<<<< HEAD
services:
  db:
    restart: unless-stopped
    image: postgres:16
    environment:
      POSTGRES_USER: coreops
      POSTGRES_PASSWORD: coreops
      POSTGRES_DB: coreops
    volumes:
      - coreops_db:/var/lib/postgresql/data

  redis:
    restart: unless-stopped
    image: redis:7


  api:
    restart: unless-stopped
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    env_file:
      - .env
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    volumes:
      - .:/code

  worker:
    restart: unless-stopped
    build: .
    command: celery -A app.workers.celery_app.celery worker --loglevel=INFO
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - .:/code

volumes:
=======
services:
  db:
    restart: unless-stopped
    image: postgres:16
    environment:
      POSTGRES_USER: coreops
      POSTGRES_PASSWORD: coreops
      POSTGRES_DB: coreops
    volumes:
      - coreops_db:/var/lib/postgresql/data

  redis:
    restart: unless-stopped
    image: redis:7


  api:
    restart: unless-stopped
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    env_file:
      - .env
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    volumes:
      - .:/code

  worker:
    restart: unless-stopped
    build: .
    command: celery -A app.workers.celery_app.celery worker --loglevel=INFO
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - .:/code

volumes:
>>>>>>> 21599b0b39eba37876fc43d9838497fbe2974000
  coreops_db: