"""add current monitor status fields

Revision ID: 1e165d1c28ef
Revises: 271a70bd9aba
Create Date: 2026-03-06 22:37:29.915998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e165d1c28ef'
down_revision: Union[str, Sequence[str], None] = '271a70bd9aba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.add_column("jobs", sa.Column("last_status", sa.String(length=30), nullable=True))
    op.add_column("jobs", sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("jobs", sa.Column("last_error", sa.Text(), nullable=True))
    op.add_column("jobs", sa.Column("last_output", sa.JSON(), nullable=True))
    op.add_column(
        "jobs",
        sa.Column("consecutive_failures", sa.Integer(), nullable=False, server_default="0")
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'consecutive_failures')
    op.drop_column('jobs', 'last_output')
    op.drop_column('jobs', 'last_error')
    op.drop_column('jobs', 'last_checked_at')
    op.drop_column('jobs', 'last_status')
    # ### end Alembic commands ###
